{% set name = "groff" %}
{% set version = "1.24.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/groff/groff-{{ version }}.tar.gz
  sha256: f9c1efd5bebbe37fc6e1063db7473ce8df1e3e0be4ff0f43ce04fce57e9c5dd9

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make
    - automake
    - gawk
    - texinfo
    - pkg-config
    - flex
    - bison
  host:
    - perl {{ perl }}
    - libiconv {{ libiconv }}  # [osx]
  run:
    - perl

test:
  commands:
    - eqn --version
    - grn --version
    - grodvi --version
    - groff --version
    - grolbp --version
    - grolj4 --version
    - grops --version
    - grotty --version
    - indxbib --version
    - post-grohtml --version
    - pre-grohtml --version
    - preconv --version
    - troff --version
    - chem --version
    - gperl --version
    - gpinyin --version
    - grog --version
    - gropdf --version
    - neqn --version
    - nroff --version
    - test -f $PREFIX/bin/glilypond
    - test -f $PREFIX/bin/afmtodit

about:
  home: https://www.gnu.org/software/groff/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: 'Groff (GNU troff) is a typesetting system'
  description: |
    The Groff package contains programs for processing and formatting text.
  doc_url: https://www.gnu.org/software/groff/#documentation
  dev_url: https://git.savannah.gnu.org/cgit/groff.git

extra:
  recipe-maintainers:
    - nehaljwani
